import type { ExerciseDefinition } from "./exercise-library";

export const ACCESSORY_EXERCISE_LIBRARY: ExerciseDefinition[] = [
  {
    id: "walk",
    name: "Chůze",
    aliases: ["walk", "walking", "chůze"],
    category: "recovery",
    movementFamily: "locomotion",
    equipment: [],
    primaryMuscles: ["nohy"],
    purposes: ["aktivní regenerace", "cool-down", "nízká intenzita"],
    instructions: ["Jdi uvolněným tempem, při kterém můžeš pohodlně mluvit."],
    cues: ["Uvolněná ramena", "Plynulý dech", "Lehký krok"],
    commonMistakes: ["Zbytečně vysoké tempo po náročné jednotce"],
    regressions: [], progressions: ["incline-walk"], alternatives: ["elliptical"],
    tags: ["walking", "recovery", "cooldown", "low-impact"],
    team: { modes: ["solo", "simultaneous"], supportsIndependentTracking: true },
  },
  {
    id: "incline-walk",
    name: "Chůze do sklonu na pásu",
    aliases: ["incline walk", "treadmill walk"],
    category: "conditioning",
    movementFamily: "locomotion",
    equipment: [{ anyOf: ["treadmill"] }],
    primaryMuscles: ["hýždě", "lýtka", "hamstringy"],
    purposes: ["low-impact conditioning", "finisher", "aerobní práce"],
    instructions: ["Zvol sklon a rychlost, které udržíš bez držení madel."],
    cues: ["Vzpřímený postoj", "Plynulý krok", "Nedrž se madel"],
    commonMistakes: ["Příliš vysoký sklon s držením madel"],
    regressions: ["walk"], progressions: [], alternatives: ["stair-climber"],
    tags: ["walking", "treadmill", "finisher", "low-impact"],
    team: { modes: ["solo", "simultaneous"], requiresSingleStation: true, supportsIndependentTracking: true },
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    aliases: ["ab wheel", "rollout"],
    category: "strength",
    movementFamily: "core",
    equipment: [{ anyOf: ["ab-wheel"] }],
    primaryMuscles: ["core", "široký sval zádový"],
    purposes: ["core strength", "finisher"],
    instructions: ["Zpevni žebra a pánev a vyjížděj jen tak daleko, dokud udržíš bedra stabilní."],
    cues: ["Žebra dolů", "Hýždě aktivní", "Kontrolovaný návrat"],
    commonMistakes: ["Propad beder", "Příliš dlouhý rozsah"],
    regressions: ["plank"], progressions: [], alternatives: ["body-saw"],
    tags: ["core", "finisher"],
    team: { modes: ["solo", "simultaneous", "shared-reps", "you-go-i-go"], supportsIndependentTracking: true },
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    aliases: ["cable crunch", "kneeling cable crunch"],
    category: "strength",
    movementFamily: "core-flexion",
    equipment: [{ anyOf: ["cable-machine"] }],
    primaryMuscles: ["břišní svaly"],
    purposes: ["hypertrofie core", "finisher"],
    instructions: ["Zkrať trup přes břišní svaly bez tahání lana pažemi."],
    cues: ["Žebra k pánvi", "Paže drží pozici", "Pomalu zpět"],
    commonMistakes: ["Tah rukama", "Pohyb jen v kyčlích"],
    regressions: ["crunch"], progressions: [], alternatives: ["weighted-sit-up"],
    tags: ["core", "cable", "finisher", "accessory"],
    team: { modes: ["solo", "shared-reps", "you-go-i-go"], requiresSingleStation: true, supportsIndependentTracking: true },
  },
  {
    id: "weighted-sit-up",
    name: "Weighted Sit-up",
    aliases: ["weighted sit up"],
    category: "strength",
    movementFamily: "core-flexion",
    equipment: [{ anyOf: ["medicine-ball", "dumbbell", "kettlebell"] }],
    primaryMuscles: ["břišní svaly", "flexory kyčle"],
    purposes: ["core strength", "finisher"],
    instructions: ["Drž lehkou zátěž stabilně a proveď kontrolovaný sed-leh."],
    cues: ["Kontrola", "Plynulý dech", "Bez švihu"],
    commonMistakes: ["Příliš těžká váha", "Švih"],
    regressions: ["sit-up"], progressions: [], alternatives: ["cable-crunch"],
    tags: ["core", "finisher", "accessory"],
    team: { modes: ["solo", "simultaneous", "shared-reps", "you-go-i-go"], supportsIndependentTracking: true },
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    aliases: ["hanging leg raise"],
    category: "strength",
    movementFamily: "core-flexion",
    equipment: [{ anyOf: ["pull-up-bar"] }],
    primaryMuscles: ["břišní svaly", "flexory kyčle", "úchop"],
    purposes: ["core strength", "grip", "finisher"],
    instructions: ["Vis drž aktivní a zvedej nohy bez nekontrolovaného rozhoupání."],
    cues: ["Aktivní ramena", "Pánev pod sebe", "Bez švihu"],
    commonMistakes: ["Velký kipping", "Pasivní ramena"],
    regressions: ["hanging-knee-raise"], progressions: ["toes-to-bar"], alternatives: ["leg-raise"],
    tags: ["core", "grip", "finisher", "gymnastics"],
    team: { modes: ["solo", "shared-reps", "you-go-i-go"], requiresSingleStation: true, supportsIndependentTracking: true },
  },
  {
    id: "dumbbell-side-bend",
    name: "Dumbbell Side Bend",
    aliases: ["side bend"],
    category: "strength",
    movementFamily: "core-rotation",
    equipment: [{ anyOf: ["dumbbell", "kettlebell"] }],
    primaryMuscles: ["šikmé břišní svaly"],
    purposes: ["core accessory", "finisher"],
    instructions: ["Nakláněj trup v malém kontrolovaném rozsahu bez rotace."],
    cues: ["Pánev stabilní", "Pomalu", "Bez rotace"],
    commonMistakes: ["Příliš velký rozsah", "Švih"],
    regressions: [], progressions: [], alternatives: ["suitcase-march"],
    tags: ["core", "finisher", "accessory"],
    team: { modes: ["solo", "simultaneous", "shared-reps"], supportsIndependentTracking: true },
  },
  {
    id: "suitcase-march",
    name: "Suitcase March",
    aliases: ["suitcase march"],
    category: "strength",
    movementFamily: "core-anti-rotation",
    equipment: [{ anyOf: ["dumbbell", "kettlebell"] }],
    primaryMuscles: ["core", "úchop", "flexory kyčle"],
    purposes: ["anti-rotation", "core finisher", "carry preparation"],
    instructions: ["Drž váhu na jedné straně a střídavě zvedej kolena bez úklonu trupu."],
    cues: ["Vysoký postoj", "Bez úklonu", "Pomalý rytmus"],
    commonMistakes: ["Naklánění k váze", "Příliš rychlé tempo"],
    regressions: ["suitcase-hold"], progressions: ["kb-suitcase-carry"], alternatives: ["cable-pallof-press"],
    tags: ["core", "grip", "finisher", "accessory"],
    team: { modes: ["solo", "simultaneous"], supportsIndependentTracking: true },
  },
  {
    id: "suitcase-hold",
    name: "Suitcase Hold",
    aliases: ["suitcase hold"],
    category: "compensation",
    movementFamily: "core-anti-rotation",
    equipment: [{ anyOf: ["dumbbell", "kettlebell"] }],
    primaryMuscles: ["core", "úchop"],
    purposes: ["anti-rotation", "grip", "finisher"],
    instructions: ["Stůj vzpřímeně s váhou na jedné straně a odolávej úklonu."],
    cues: ["Ramena stejně vysoko", "Žebra nad pánví", "Plynule dýchej"],
    commonMistakes: ["Úklon", "Zadržování dechu"],
    regressions: [], progressions: ["suitcase-march"], alternatives: ["side-plank"],
    tags: ["core", "grip", "finisher", "prehab"],
    team: { modes: ["solo", "simultaneous"], supportsIndependentTracking: true },
  },
  {
    id: "plank-dumbbell-drag",
    name: "Plank Dumbbell Drag",
    aliases: ["plank drag"],
    category: "conditioning",
    movementFamily: "core-anti-rotation",
    equipment: [{ anyOf: ["dumbbell", "kettlebell"] }],
    primaryMuscles: ["core", "ramena"],
    purposes: ["anti-rotation", "core finisher"],
    instructions: ["Z planku přetahuj zátěž pod tělem bez rotace pánve."],
    cues: ["Široký postoj", "Pánev rovně", "Pomalu"],
    commonMistakes: ["Rotace pánve", "Švih"],
    regressions: ["plank-shoulder-tap"], progressions: [], alternatives: ["db-renegade-row"],
    tags: ["core", "finisher", "dumbbell"],
    team: { modes: ["solo", "simultaneous", "shared-reps", "you-go-i-go"], supportsIndependentTracking: true },
  },
  {
    id: "dead-hang",
    name: "Dead Hang",
    aliases: ["dead hang"],
    category: "compensation",
    movementFamily: "vertical-pull",
    equipment: [{ anyOf: ["pull-up-bar"] }],
    primaryMuscles: ["úchop", "ramena", "záda"],
    purposes: ["grip", "dekomprese", "finisher"],
    instructions: ["Vis v kontrolované pozici a ukonči sérii před ztrátou bezpečného úchopu."],
    cues: ["Plynule dýchej", "Bez bolesti ramen", "Kontrolovaný sestup"],
    commonMistakes: ["Pokračování přes bolest", "Nekontrolované seskočení"],
    regressions: [], progressions: ["scapular-pull-up"], alternatives: ["farmer-carry"],
    tags: ["grip", "finisher", "recovery"],
    team: { modes: ["solo", "you-go-i-go"], requiresSingleStation: true, supportsIndependentTracking: true },
  },
  {
    id: "scapular-pull-up",
    name: "Scapular Pull-up",
    aliases: ["scap pull up"],
    category: "compensation",
    movementFamily: "vertical-pull",
    equipment: [{ anyOf: ["pull-up-bar"] }],
    primaryMuscles: ["lopatky", "záda", "ramena"],
    purposes: ["aktivace lopatek", "prehab", "příprava na hrazdu"],
    instructions: ["Z visu bez ohýbání loktů stáhni lopatky dolů a lehce zvedni tělo."],
    cues: ["Lokty rovné", "Ramena od uší", "Malý kontrolovaný pohyb"],
    commonMistakes: ["Ohýbání loktů", "Švih"],
    regressions: ["dead-hang"], progressions: ["pull-up"], alternatives: ["band-pull-apart"],
    tags: ["prehab", "shoulders", "gymnastics"],
    team: { modes: ["solo", "simultaneous"], supportsIndependentTracking: true },
  },
  {
    id: "wall-sit",
    name: "Wall Sit",
    aliases: ["wall sit"],
    category: "conditioning",
    movementFamily: "squat",
    equipment: [],
    primaryMuscles: ["kvadricepsy", "hýždě"],
    purposes: ["lokální vytrvalost", "finisher", "bez vybavení"],
    instructions: ["Opři záda o stěnu a drž stabilní dřepovou pozici."],
    cues: ["Celé chodidlo", "Kolena stabilní", "Plynule dýchej"],
    commonMistakes: ["Kolena padají dovnitř", "Zadržování dechu"],
    regressions: [], progressions: [], alternatives: ["air-squat"],
    tags: ["bodyweight", "legs", "finisher"],
    team: { modes: ["solo", "simultaneous"], supportsIndependentTracking: true },
  },
  {
    id: "tibialis-raise",
    name: "Tibialis Raise",
    aliases: ["tib raise"],
    category: "compensation",
    movementFamily: "calf",
    equipment: [],
    primaryMuscles: ["přední strana bérce"],
    purposes: ["running prehab", "kotník", "kompenzace"],
    instructions: ["Opři se o stěnu a zvedej špičky při patách na zemi."],
    cues: ["Paty dole", "Kontrola", "Plný rozsah"],
    commonMistakes: ["Houpání tělem", "Příliš rychlé opakování"],
    regressions: [], progressions: [], alternatives: ["calf-raise-bodyweight"],
    tags: ["running-prehab", "calves", "prehab"],
    team: { modes: ["solo", "simultaneous"], supportsIndependentTracking: true },
  },
  {
    id: "soleus-calf-raise",
    name: "Bent-knee Soleus Raise",
    aliases: ["soleus raise", "bent knee calf raise"],
    category: "compensation",
    movementFamily: "calf",
    equipment: [],
    primaryMuscles: ["soleus", "lýtka"],
    purposes: ["running prehab", "lýtka", "kompenzace"],
    instructions: ["S lehce pokrčenými koleny zvedej paty kontrolovaně nahoru a dolů."],
    cues: ["Kolena pokrčená", "Pomalý návrat", "Tlak přes palec"],
    commonMistakes: ["Propnutí kolen", "Odskakování"],
    regressions: [], progressions: [], alternatives: ["calf-raise-bodyweight"],
    tags: ["running-prehab", "calves", "prehab"],
    team: { modes: ["solo", "simultaneous"], supportsIndependentTracking: true },
  },
];
