import type { EquipmentId } from "./types";
import type { ExerciseCategory, ExerciseDefinition, TeamWorkMode } from "./exercise-library";

type ExerciseSeed = {
  id: string;
  name: string;
  category: ExerciseCategory;
  family: string;
  equipment?: EquipmentId[][];
  tags?: string[];
  aliases?: string[];
  singleStation?: boolean;
};

const FAMILY_MUSCLES: Record<string, string[]> = {
  squat: ["kvadricepsy", "hýždě", "core"],
  lunge: ["kvadricepsy", "hýždě", "hamstringy", "core"],
  hinge: ["hamstringy", "hýždě", "záda", "core"],
  "horizontal-push": ["hrudník", "triceps", "ramena"],
  "vertical-push": ["ramena", "triceps", "core"],
  "horizontal-pull": ["záda", "biceps", "zadní ramena"],
  "vertical-pull": ["široký sval zádový", "biceps", "core"],
  carry: ["úchop", "core", "trapézy", "nohy"],
  core: ["core"],
  "core-flexion": ["břišní svaly", "flexory kyčle"],
  "core-rotation": ["šikmé břišní svaly", "core"],
  "core-anti-rotation": ["core", "šikmé břišní svaly"],
  "posterior-chain": ["hýždě", "hamstringy", "vzpřimovače páteře"],
  olympic: ["celé tělo", "hýždě", "kvadricepsy", "ramena"],
  gymnastics: ["záda", "ramena", "core", "paže"],
  jump: ["kvadricepsy", "hýždě", "lýtka"],
  burpee: ["celé tělo", "ramena", "nohy", "core"],
  locomotion: ["nohy", "core", "ramena"],
  cardio: ["kardiovaskulární systém", "nohy"],
  conditioning: ["celé tělo"],
  shoulder: ["ramena", "lopatky"],
  arms: ["biceps", "triceps"],
  calf: ["lýtka"],
  hip: ["hýždě", "kyčle"],
  mobility: ["mobilita", "kontrola pohybu"],
};

const FAMILY_GUIDANCE: Record<string, { instructions: string[]; cues: string[]; mistakes: string[] }> = {
  squat: {
    instructions: ["Drž celé chodidlo v kontaktu se zemí a kontrolovaně klesej do dřepu.", "Vrať se vzhůru tlakem přes celé chodidlo."],
    cues: ["Kolena sledují špičky", "Pevný střed", "Celé chodidlo"],
    mistakes: ["Kolena padají dovnitř", "Zvedání pat", "Ztráta neutrální polohy trupu"],
  },
  lunge: {
    instructions: ["Udělej stabilní krok a kontrolovaně sniž těžiště.", "Odraz se přes celé přední chodidlo a drž pánev stabilní."],
    cues: ["Stabilní koleno", "Pevný trup", "Kontrolovaný krok"],
    mistakes: ["Koleno padá dovnitř", "Příliš úzký postoj", "Ztráta rovnováhy"],
  },
  hinge: {
    instructions: ["Posuň kyčle dozadu a drž páteř stabilní.", "Vrať se do stoje aktivací hýždí bez přehnaného záklonu."],
    cues: ["Kyčle dozadu", "Dlouhá páteř", "Tlak přes chodidla"],
    mistakes: ["Kulatá záda", "Dřep místo hip hinge", "Přehnaný záklon nahoře"],
  },
  "horizontal-push": {
    instructions: ["Drž lopatky stabilní a tlač zátěž plynule od těla.", "Vrať se pod kontrolou do výchozí pozice."],
    cues: ["Pevný střed", "Kontrolovaná dráha", "Zápěstí stabilní"],
    mistakes: ["Zvedání ramen", "Nekontrolovaný návrat", "Ztráta pozice trupu"],
  },
  "vertical-push": {
    instructions: ["Zpevni trup a vytlač zátěž nad hlavu bez prohnutí beder.", "Vrať zátěž pod kontrolou."],
    cues: ["Žebra dolů", "Hlava mezi pažemi", "Pevné nohy"],
    mistakes: ["Prohnutí beder", "Tlak před tělem", "Ztráta kontroly"],
  },
  "horizontal-pull": {
    instructions: ["Začni stažením lopatek a přitáhni zátěž k trupu.", "Vrať se plynule bez ztráty napětí."],
    cues: ["Lokty dozadu", "Ramena dolů", "Pevný trup"],
    mistakes: ["Krčení ramen", "Švih trupem", "Tah pouze pažemi"],
  },
  "vertical-pull": {
    instructions: ["Stáhni lopatky a táhni lokty směrem dolů.", "Vrať se do plného kontrolovaného protažení."],
    cues: ["Hrudník vysoko", "Lokty dolů", "Bez švihu"],
    mistakes: ["Tah krkem", "Švihání", "Zkrácený rozsah"],
  },
  core: {
    instructions: ["Zpevni střed těla a udrž neutrální polohu pánve.", "Pohyb prováděj pomalu a bez ztráty napětí."],
    cues: ["Žebra dolů", "Pánev stabilní", "Plynule dýchej"],
    mistakes: ["Prohnutí beder", "Zadržování dechu", "Příliš rychlé tempo"],
  },
  "core-flexion": {
    instructions: ["Pohyb zahaj aktivací břicha a pracuj v kontrolovaném rozsahu.", "Vracej se pomalu bez tahu za krk."],
    cues: ["Břicho pracuje", "Pomalu", "Krk uvolněný"],
    mistakes: ["Tah za hlavu", "Švih", "Ztráta kontroly beder"],
  },
  "core-rotation": {
    instructions: ["Rotuj trup kontrolovaně a drž pánev co nejstabilnější.", "V obou směrech zachovej stejný rozsah."],
    cues: ["Rotace z trupu", "Pevná pánev", "Kontrola"],
    mistakes: ["Švih", "Kolaps trupu", "Příliš velký rozsah bez kontroly"],
  },
  "core-anti-rotation": {
    instructions: ["Zpevni trup proti síle, která tě chce otočit.", "Udrž ramena a pánev v jedné linii."],
    cues: ["Nehýbej trupem", "Pevná pánev", "Dýchej"],
    mistakes: ["Rotace trupu", "Zadržování dechu", "Příliš vysoká zátěž"],
  },
  olympic: {
    instructions: ["Drž osu blízko těla a vytvářej sílu primárně nohama a kyčlemi.", "Techniku upřednostni před hmotností a rychlostí."],
    cues: ["Osa blízko", "Silné nohy", "Rychlé lokty / aktivní ramena"],
    mistakes: ["Tah jen rukama", "Osa daleko od těla", "Příliš těžká zátěž pro techniku"],
  },
  gymnastics: {
    instructions: ["Začni z aktivní a stabilní pozice ramen.", "Rozsah a tempo přizpůsob úrovni techniky."],
    cues: ["Aktivní ramena", "Pevný střed", "Kontrolovaný rytmus"],
    mistakes: ["Ztráta kontroly ramen", "Nadměrný švih", "Pokračování přes bolest"],
  },
  mobility: {
    instructions: ["Pohybuj se pomalu do pohodlného rozsahu bez bolesti.", "Dýchej plynule a nesnaž se rozsah vynutit."],
    cues: ["Bez bolesti", "Plynulý dech", "Kontrolovaný rozsah"],
    mistakes: ["Švihání", "Zadržování dechu", "Tlačení přes bolest"],
  },
};

const defaultGuidance = {
  instructions: ["Proveď pohyb kontrolovaně v rozsahu, který udržíš bez ztráty techniky."],
  cues: ["Pevný střed", "Kontrolovaný rytmus", "Kvalita před rychlostí"],
  mistakes: ["Příliš rychlé tempo", "Ztráta kontroly", "Nevhodně vysoká zátěž"],
};

function teamModes(seed: ExerciseSeed): TeamWorkMode[] {
  if (["mobility", "compensation", "recovery", "warmup"].includes(seed.category)) return ["solo", "simultaneous"];
  if (["cardio", "locomotion", "carry"].includes(seed.family)) return ["solo", "simultaneous", "shared-distance", "relay", "you-go-i-go"];
  return ["solo", "simultaneous", "shared-reps", "you-go-i-go"];
}

function build(seed: ExerciseSeed): ExerciseDefinition {
  const guide = FAMILY_GUIDANCE[seed.family] ?? defaultGuidance;
  const tags = [...new Set([seed.category, seed.family, ...(seed.tags ?? [])])];
  const purposes = [
    seed.category === "compensation" ? "kompenzace" : seed.category,
    seed.family,
    ...(tags.includes("finisher") ? ["finisher / dojížďka"] : []),
    ...(tags.includes("prehab") ? ["prehab / prevence přetížení"] : []),
  ];
  return {
    id: seed.id,
    name: seed.name,
    aliases: seed.aliases ?? [],
    category: seed.category,
    movementFamily: seed.family,
    equipment: (seed.equipment ?? []).map((anyOf) => ({ anyOf })),
    primaryMuscles: FAMILY_MUSCLES[seed.family] ?? ["celé tělo"],
    purposes: [...new Set(purposes)],
    instructions: guide.instructions,
    cues: guide.cues,
    commonMistakes: guide.mistakes,
    regressions: [],
    progressions: [],
    alternatives: [],
    tags,
    team: {
      modes: teamModes(seed),
      requiresSingleStation: seed.singleStation || undefined,
      supportsIndependentTracking: true,
    },
  };
}

const SEEDS: ExerciseSeed[] = [
  // Vlastní váha, core a jednoduché finishery
  { id: "push-up", name: "Push-up", category: "strength", family: "horizontal-push", tags: ["bodyweight", "upper-body"] },
  { id: "knee-push-up", name: "Push-up z kolen", category: "strength", family: "horizontal-push", tags: ["bodyweight", "regression"] },
  { id: "incline-push-up", name: "Incline Push-up", category: "strength", family: "horizontal-push", equipment: [["bench", "box"]], tags: ["bodyweight", "regression"] },
  { id: "decline-push-up", name: "Decline Push-up", category: "strength", family: "horizontal-push", equipment: [["bench", "box"]], tags: ["bodyweight", "progression"] },
  { id: "diamond-push-up", name: "Diamond Push-up", category: "strength", family: "horizontal-push", tags: ["bodyweight", "triceps"] },
  { id: "pike-push-up", name: "Pike Push-up", category: "strength", family: "vertical-push", tags: ["bodyweight", "shoulders"] },
  { id: "hand-release-push-up", name: "Hand-release Push-up", category: "conditioning", family: "horizontal-push", tags: ["bodyweight", "crossfit"] },
  { id: "burpee", name: "Burpee", category: "conditioning", family: "burpee", tags: ["bodyweight", "finisher", "crossfit"] },
  { id: "burpee-step-back", name: "Burpee Step-back", category: "conditioning", family: "burpee", tags: ["bodyweight", "low-impact"] },
  { id: "mountain-climber", name: "Mountain Climber", category: "conditioning", family: "core", tags: ["bodyweight", "core", "finisher"] },
  { id: "bear-crawl", name: "Bear Crawl", category: "conditioning", family: "locomotion", tags: ["bodyweight", "core", "shoulders"] },
  { id: "crab-walk", name: "Crab Walk", category: "conditioning", family: "locomotion", tags: ["bodyweight", "core"] },
  { id: "inchworm", name: "Inchworm", category: "warmup", family: "locomotion", tags: ["bodyweight", "mobility"] },
  { id: "plank", name: "Plank", category: "compensation", family: "core", tags: ["bodyweight", "core", "finisher"] },
  { id: "side-plank", name: "Side Plank", category: "compensation", family: "core", tags: ["bodyweight", "core", "prehab"] },
  { id: "reverse-plank", name: "Reverse Plank", category: "compensation", family: "core", tags: ["bodyweight", "posterior-chain"] },
  { id: "hollow-hold", name: "Hollow Hold", category: "strength", family: "core", tags: ["bodyweight", "gymnastics", "core"] },
  { id: "hollow-rock", name: "Hollow Rock", category: "conditioning", family: "core", tags: ["bodyweight", "gymnastics", "core", "finisher"] },
  { id: "v-up", name: "V-up", category: "conditioning", family: "core-flexion", tags: ["bodyweight", "core", "finisher"] },
  { id: "sit-up", name: "Sit-up", category: "conditioning", family: "core-flexion", tags: ["bodyweight", "core", "finisher"] },
  { id: "butterfly-sit-up", name: "Butterfly Sit-up", category: "conditioning", family: "core-flexion", tags: ["bodyweight", "crossfit", "core", "finisher"] },
  { id: "crunch", name: "Crunch", category: "strength", family: "core-flexion", tags: ["bodyweight", "core", "finisher"] },
  { id: "reverse-crunch", name: "Reverse Crunch", category: "strength", family: "core-flexion", tags: ["bodyweight", "core", "finisher"] },
  { id: "bicycle-crunch", name: "Bicycle Crunch", category: "conditioning", family: "core-rotation", tags: ["bodyweight", "core", "finisher"] },
  { id: "heel-touch", name: "Heel Touch", category: "conditioning", family: "core-rotation", tags: ["bodyweight", "core", "finisher"] },
  { id: "leg-raise", name: "Leg Raise", category: "strength", family: "core-flexion", tags: ["bodyweight", "core", "finisher"] },
  { id: "flutter-kick", name: "Flutter Kick", category: "conditioning", family: "core", tags: ["bodyweight", "core", "finisher"] },
  { id: "russian-twist", name: "Russian Twist", category: "conditioning", family: "core-rotation", tags: ["bodyweight", "core", "finisher"] },
  { id: "plank-shoulder-tap", name: "Plank Shoulder Tap", category: "conditioning", family: "core-anti-rotation", tags: ["bodyweight", "core", "shoulders"] },
  { id: "plank-jack", name: "Plank Jack", category: "conditioning", family: "core", tags: ["bodyweight", "core", "finisher"] },
  { id: "glute-bridge", name: "Glute Bridge", category: "compensation", family: "posterior-chain", tags: ["bodyweight", "glutes", "prehab"] },
  { id: "single-leg-glute-bridge", name: "Single-leg Glute Bridge", category: "strength", family: "posterior-chain", tags: ["bodyweight", "unilateral", "glutes"] },
  { id: "calf-raise-bodyweight", name: "Bodyweight Calf Raise", category: "compensation", family: "calf", tags: ["bodyweight", "calves", "running-prehab"] },
  { id: "reverse-lunge", name: "Reverse Lunge", category: "strength", family: "lunge", tags: ["bodyweight", "unilateral"] },
  { id: "split-squat", name: "Split Squat", category: "strength", family: "lunge", tags: ["bodyweight", "unilateral"] },

  // Kettlebell
  { id: "kb-goblet-squat", name: "Kettlebell Goblet Squat", category: "strength", family: "squat", equipment: [["kettlebell"]], tags: ["kettlebell"] },
  { id: "kb-front-rack-squat", name: "Kettlebell Front Rack Squat", category: "strength", family: "squat", equipment: [["kettlebell"]], tags: ["kettlebell"] },
  { id: "kb-deadlift", name: "Kettlebell Deadlift", category: "strength", family: "hinge", equipment: [["kettlebell"]], tags: ["kettlebell"] },
  { id: "kb-rdl", name: "Kettlebell Romanian Deadlift", category: "strength", family: "hinge", equipment: [["kettlebell"]], tags: ["kettlebell"] },
  { id: "kb-sumo-deadlift", name: "Kettlebell Sumo Deadlift", category: "strength", family: "hinge", equipment: [["kettlebell"]], tags: ["kettlebell"] },
  { id: "kb-swing", name: "Kettlebell Swing", category: "conditioning", family: "hinge", equipment: [["kettlebell"]], tags: ["kettlebell", "crossfit", "finisher"] },
  { id: "kb-american-swing", name: "American Kettlebell Swing", category: "conditioning", family: "hinge", equipment: [["kettlebell"]], tags: ["kettlebell", "crossfit"] },
  { id: "kb-clean", name: "Kettlebell Clean", category: "conditioning", family: "olympic", equipment: [["kettlebell"]], tags: ["kettlebell"] },
  { id: "kb-clean-press", name: "Kettlebell Clean & Press", category: "conditioning", family: "olympic", equipment: [["kettlebell"]], tags: ["kettlebell", "full-body"] },
  { id: "kb-snatch", name: "Kettlebell Snatch", category: "conditioning", family: "olympic", equipment: [["kettlebell"]], tags: ["kettlebell", "crossfit"] },
  { id: "kb-strict-press", name: "Kettlebell Strict Press", category: "strength", family: "vertical-push", equipment: [["kettlebell"]], tags: ["kettlebell"] },
  { id: "kb-push-press", name: "Kettlebell Push Press", category: "conditioning", family: "vertical-push", equipment: [["kettlebell"]], tags: ["kettlebell"] },
  { id: "kb-row", name: "Kettlebell Row", category: "strength", family: "horizontal-pull", equipment: [["kettlebell"]], tags: ["kettlebell"] },
  { id: "kb-renegade-row", name: "Kettlebell Renegade Row", category: "strength", family: "core-anti-rotation", equipment: [["kettlebell"]], tags: ["kettlebell", "core"] },
  { id: "kb-lunge", name: "Kettlebell Walking Lunge", category: "strength", family: "lunge", equipment: [["kettlebell"]], tags: ["kettlebell", "unilateral"] },
  { id: "kb-reverse-lunge", name: "Kettlebell Reverse Lunge", category: "strength", family: "lunge", equipment: [["kettlebell"]], tags: ["kettlebell", "unilateral"] },
  { id: "kb-step-up", name: "Kettlebell Step-up", category: "strength", family: "lunge", equipment: [["kettlebell"], ["box", "bench"]], tags: ["kettlebell", "unilateral"] },
  { id: "kb-suitcase-carry", name: "Kettlebell Suitcase Carry", category: "strength", family: "carry", equipment: [["kettlebell"]], tags: ["kettlebell", "core", "grip"] },
  { id: "kb-front-rack-carry", name: "Kettlebell Front Rack Carry", category: "strength", family: "carry", equipment: [["kettlebell"]], tags: ["kettlebell", "core"] },
  { id: "kb-turkish-get-up", name: "Turkish Get-up", category: "strength", family: "core", equipment: [["kettlebell"]], tags: ["kettlebell", "shoulder-stability", "core"] },

  // Dumbbell
  { id: "db-goblet-squat", name: "Dumbbell Goblet Squat", category: "strength", family: "squat", equipment: [["dumbbell"]], tags: ["dumbbell"] },
  { id: "dumbbell-front-squat", name: "Dumbbell Front Squat", category: "strength", family: "squat", equipment: [["dumbbell"]], tags: ["dumbbell"] },
  { id: "db-split-squat", name: "Dumbbell Split Squat", category: "strength", family: "lunge", equipment: [["dumbbell"]], tags: ["dumbbell", "unilateral"] },
  { id: "db-bulgarian-split-squat", name: "Dumbbell Bulgarian Split Squat", category: "strength", family: "lunge", equipment: [["dumbbell"], ["bench", "box"]], tags: ["dumbbell", "unilateral"] },
  { id: "dumbbell-lunge", name: "Dumbbell Walking Lunge", category: "strength", family: "lunge", equipment: [["dumbbell"]], tags: ["dumbbell", "unilateral"] },
  { id: "db-reverse-lunge", name: "Dumbbell Reverse Lunge", category: "strength", family: "lunge", equipment: [["dumbbell"]], tags: ["dumbbell", "unilateral"] },
  { id: "db-step-up", name: "Dumbbell Step-up", category: "strength", family: "lunge", equipment: [["dumbbell"], ["box", "bench"]], tags: ["dumbbell", "unilateral"] },
  { id: "db-rdl", name: "Dumbbell Romanian Deadlift", category: "strength", family: "hinge", equipment: [["dumbbell"]], tags: ["dumbbell"] },
  { id: "db-deadlift", name: "Dumbbell Deadlift", category: "strength", family: "hinge", equipment: [["dumbbell"]], tags: ["dumbbell"] },
  { id: "db-sumo-deadlift", name: "Dumbbell Sumo Deadlift", category: "strength", family: "hinge", equipment: [["dumbbell"]], tags: ["dumbbell"] },
  { id: "db-bench-press", name: "Dumbbell Bench Press", category: "strength", family: "horizontal-push", equipment: [["dumbbell"], ["bench"]], tags: ["dumbbell", "chest"] },
  { id: "db-incline-bench-press", name: "Dumbbell Incline Bench Press", category: "strength", family: "horizontal-push", equipment: [["dumbbell"], ["bench"]], tags: ["dumbbell", "chest"] },
  { id: "db-floor-press", name: "Dumbbell Floor Press", category: "strength", family: "horizontal-push", equipment: [["dumbbell"]], tags: ["dumbbell", "chest"] },
  { id: "db-shoulder-press", name: "Dumbbell Shoulder Press", category: "strength", family: "vertical-push", equipment: [["dumbbell"]], tags: ["dumbbell", "shoulders"] },
  { id: "db-push-press", name: "Dumbbell Push Press", category: "conditioning", family: "vertical-push", equipment: [["dumbbell"]], tags: ["dumbbell", "crossfit"] },
  { id: "db-lateral-raise", name: "Dumbbell Lateral Raise", category: "strength", family: "shoulder", equipment: [["dumbbell"]], tags: ["dumbbell", "shoulders", "accessory"] },
  { id: "db-front-raise", name: "Dumbbell Front Raise", category: "strength", family: "shoulder", equipment: [["dumbbell"]], tags: ["dumbbell", "shoulders", "accessory"] },
  { id: "db-bent-over-row", name: "Dumbbell Bent-over Row", category: "strength", family: "horizontal-pull", equipment: [["dumbbell"]], tags: ["dumbbell", "back"] },
  { id: "db-one-arm-row", name: "One-arm Dumbbell Row", category: "strength", family: "horizontal-pull", equipment: [["dumbbell"], ["bench", "none"]], tags: ["dumbbell", "back", "unilateral"] },
  { id: "db-renegade-row", name: "Dumbbell Renegade Row", category: "strength", family: "core-anti-rotation", equipment: [["dumbbell"]], tags: ["dumbbell", "core"] },
  { id: "db-biceps-curl", name: "Dumbbell Biceps Curl", category: "strength", family: "arms", equipment: [["dumbbell"]], tags: ["dumbbell", "arms", "accessory"] },
  { id: "db-hammer-curl", name: "Dumbbell Hammer Curl", category: "strength", family: "arms", equipment: [["dumbbell"]], tags: ["dumbbell", "arms", "accessory"] },
  { id: "db-triceps-extension", name: "Dumbbell Overhead Triceps Extension", category: "strength", family: "arms", equipment: [["dumbbell"]], tags: ["dumbbell", "arms", "accessory"] },
  { id: "db-devils-press", name: "Devil's Press", category: "conditioning", family: "conditioning", equipment: [["dumbbell"]], tags: ["dumbbell", "crossfit", "full-body", "finisher"] },
  { id: "db-man-maker", name: "Man Maker", category: "conditioning", family: "conditioning", equipment: [["dumbbell"]], tags: ["dumbbell", "crossfit", "full-body", "finisher"] },

  // Osa, rack a olympijské prvky
  { id: "back-squat", name: "Back Squat", category: "strength", family: "squat", equipment: [["barbell"], ["rack"]], tags: ["barbell", "legs"] },
  { id: "front-squat", name: "Front Squat", category: "strength", family: "squat", equipment: [["barbell"], ["rack"]], tags: ["barbell", "crossfit"] },
  { id: "overhead-squat", name: "Overhead Squat", category: "strength", family: "squat", equipment: [["barbell"]], tags: ["barbell", "crossfit", "mobility"] },
  { id: "barbell-box-squat", name: "Barbell Box Squat", category: "strength", family: "squat", equipment: [["barbell"], ["rack"], ["box", "bench"]], tags: ["barbell"] },
  { id: "zercher-squat", name: "Zercher Squat", category: "strength", family: "squat", equipment: [["barbell"]], tags: ["barbell", "core"] },
  { id: "deadlift", name: "Deadlift", category: "strength", family: "hinge", equipment: [["barbell"]], tags: ["barbell", "posterior-chain"] },
  { id: "romanian-deadlift", name: "Romanian Deadlift", category: "strength", family: "hinge", equipment: [["barbell"]], tags: ["barbell", "posterior-chain"] },
  { id: "sumo-deadlift", name: "Sumo Deadlift", category: "strength", family: "hinge", equipment: [["barbell"]], tags: ["barbell", "posterior-chain"] },
  { id: "trap-bar-deadlift", name: "Trap Bar Deadlift", category: "strength", family: "hinge", equipment: [["trap-bar"]], tags: ["trap-bar", "posterior-chain"] },
  { id: "good-morning", name: "Barbell Good Morning", category: "strength", family: "hinge", equipment: [["barbell"], ["rack"]], tags: ["barbell", "posterior-chain"] },
  { id: "barbell-hip-thrust", name: "Barbell Hip Thrust", category: "strength", family: "posterior-chain", equipment: [["barbell"], ["bench"]], tags: ["barbell", "glutes"] },
  { id: "bench-press", name: "Bench Press", category: "strength", family: "horizontal-push", equipment: [["barbell"], ["bench"], ["rack"]], tags: ["barbell", "chest"] },
  { id: "incline-bench-press", name: "Incline Bench Press", category: "strength", family: "horizontal-push", equipment: [["barbell"], ["bench"], ["rack"]], tags: ["barbell", "chest"] },
  { id: "close-grip-bench-press", name: "Close-grip Bench Press", category: "strength", family: "horizontal-push", equipment: [["barbell"], ["bench"], ["rack"]], tags: ["barbell", "triceps"] },
  { id: "strict-press", name: "Barbell Strict Press", category: "strength", family: "vertical-push", equipment: [["barbell"], ["rack"]], tags: ["barbell", "shoulders"] },
  { id: "push-press", name: "Barbell Push Press", category: "conditioning", family: "vertical-push", equipment: [["barbell"]], tags: ["barbell", "crossfit"] },
  { id: "push-jerk", name: "Push Jerk", category: "conditioning", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit"] },
  { id: "split-jerk", name: "Split Jerk", category: "strength", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit", "olympic"] },
  { id: "bent-over-row", name: "Barbell Bent-over Row", category: "strength", family: "horizontal-pull", equipment: [["barbell"]], tags: ["barbell", "back"] },
  { id: "pendlay-row", name: "Pendlay Row", category: "strength", family: "horizontal-pull", equipment: [["barbell"]], tags: ["barbell", "back"] },
  { id: "barbell-lunge", name: "Barbell Walking Lunge", category: "strength", family: "lunge", equipment: [["barbell"]], tags: ["barbell", "unilateral"] },
  { id: "barbell-reverse-lunge", name: "Barbell Reverse Lunge", category: "strength", family: "lunge", equipment: [["barbell"], ["rack"]], tags: ["barbell", "unilateral"] },
  { id: "barbell-step-up", name: "Barbell Step-up", category: "strength", family: "lunge", equipment: [["barbell"], ["box", "bench"]], tags: ["barbell", "unilateral"] },
  { id: "barbell-thruster", name: "Barbell Thruster", category: "conditioning", family: "squat", equipment: [["barbell"]], tags: ["barbell", "crossfit", "finisher"] },
  { id: "clean", name: "Clean", category: "strength", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit", "olympic"] },
  { id: "power-clean", name: "Power Clean", category: "conditioning", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit", "olympic"] },
  { id: "hang-power-clean", name: "Hang Power Clean", category: "conditioning", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit", "olympic"] },
  { id: "squat-clean", name: "Squat Clean", category: "strength", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit", "olympic"] },
  { id: "clean-pull", name: "Clean Pull", category: "strength", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "olympic"] },
  { id: "snatch", name: "Snatch", category: "strength", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit", "olympic"] },
  { id: "power-snatch", name: "Power Snatch", category: "conditioning", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit", "olympic"] },
  { id: "hang-power-snatch", name: "Hang Power Snatch", category: "conditioning", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit", "olympic"] },
  { id: "snatch-pull", name: "Snatch Pull", category: "strength", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "olympic"] },
  { id: "barbell-high-pull", name: "Barbell High Pull", category: "conditioning", family: "olympic", equipment: [["barbell"]], tags: ["barbell", "crossfit"] },
  { id: "landmine-press", name: "Landmine Press", category: "strength", family: "vertical-push", equipment: [["landmine"]], tags: ["landmine", "shoulders"] },

  // Hrazda, kruhy a CrossFit / gymnastics
  { id: "pull-up", name: "Pull-up", category: "strength", family: "vertical-pull", equipment: [["pull-up-bar"]], tags: ["bodyweight", "gymnastics"] },
  { id: "chin-up", name: "Chin-up", category: "strength", family: "vertical-pull", equipment: [["pull-up-bar"]], tags: ["bodyweight", "gymnastics"] },
  { id: "strict-pull-up", name: "Strict Pull-up", category: "strength", family: "vertical-pull", equipment: [["pull-up-bar"]], tags: ["bodyweight", "gymnastics"] },
  { id: "banded-pull-up", name: "Banded Pull-up", category: "strength", family: "vertical-pull", equipment: [["pull-up-bar"], ["resistance-band"]], tags: ["bodyweight", "gymnastics", "regression"] },
  { id: "jumping-pull-up", name: "Jumping Pull-up", category: "conditioning", family: "vertical-pull", equipment: [["pull-up-bar"], ["box", "bench"]], tags: ["bodyweight", "crossfit", "regression"] },
  { id: "kipping-pull-up", name: "Kipping Pull-up", category: "conditioning", family: "gymnastics", equipment: [["pull-up-bar"]], tags: ["bodyweight", "crossfit"] },
  { id: "chest-to-bar", name: "Chest-to-bar Pull-up", category: "conditioning", family: "gymnastics", equipment: [["pull-up-bar"]], tags: ["bodyweight", "crossfit"] },
  { id: "toes-to-bar", name: "Toes-to-bar", category: "conditioning", family: "gymnastics", equipment: [["pull-up-bar"]], tags: ["bodyweight", "crossfit", "core", "finisher"] },
  { id: "hanging-knee-raise", name: "Hanging Knee Raise", category: "strength", family: "core-flexion", equipment: [["pull-up-bar"]], tags: ["bodyweight", "core", "finisher"] },
  { id: "bar-muscle-up", name: "Bar Muscle-up", category: "conditioning", family: "gymnastics", equipment: [["pull-up-bar"]], tags: ["bodyweight", "crossfit", "advanced"] },
  { id: "ring-row", name: "Ring Row", category: "strength", family: "horizontal-pull", equipment: [["rings", "suspension-trainer"]], tags: ["bodyweight", "gymnastics"] },
  { id: "ring-dip", name: "Ring Dip", category: "strength", family: "gymnastics", equipment: [["rings"]], tags: ["bodyweight", "gymnastics"] },
  { id: "ring-muscle-up", name: "Ring Muscle-up", category: "conditioning", family: "gymnastics", equipment: [["rings"]], tags: ["bodyweight", "crossfit", "advanced"] },
  { id: "dip", name: "Dip", category: "strength", family: "horizontal-push", equipment: [["dip-bars", "rings"]], tags: ["bodyweight", "triceps"] },
  { id: "box-jump", name: "Box Jump", category: "conditioning", family: "jump", equipment: [["box"]], tags: ["crossfit", "plyometric", "finisher"] },
  { id: "step-up", name: "Box Step-up", category: "strength", family: "lunge", equipment: [["box", "bench"]], tags: ["unilateral"] },
  { id: "box-step-over", name: "Box Step-over", category: "conditioning", family: "lunge", equipment: [["box"]], tags: ["crossfit", "conditioning"] },
  { id: "burpee-box-jump", name: "Burpee Box Jump", category: "conditioning", family: "burpee", equipment: [["box"]], tags: ["crossfit", "finisher"] },
  { id: "burpee-box-jump-over", name: "Burpee Box Jump-over", category: "conditioning", family: "burpee", equipment: [["box"]], tags: ["crossfit", "finisher"] },
  { id: "wall-walk", name: "Wall Walk", category: "conditioning", family: "gymnastics", tags: ["bodyweight", "crossfit", "shoulders"] },
  { id: "handstand-hold", name: "Handstand Hold", category: "strength", family: "gymnastics", tags: ["bodyweight", "gymnastics", "shoulders"] },
  { id: "handstand-push-up", name: "Handstand Push-up", category: "strength", family: "gymnastics", tags: ["bodyweight", "crossfit", "advanced"] },
  { id: "double-under", name: "Double Under", category: "conditioning", family: "cardio", equipment: [["jump-rope"]], tags: ["crossfit", "cardio", "finisher"] },
  { id: "single-under", name: "Single Under", category: "conditioning", family: "cardio", equipment: [["jump-rope"]], tags: ["cardio", "warmup"] },
  { id: "ring-push-up", name: "Ring Push-up", category: "strength", family: "horizontal-push", equipment: [["rings"]], tags: ["bodyweight", "gymnastics"] },

  // Stroje a kladky běžné posilovny
  { id: "machine-leg-press", name: "Leg Press", category: "strength", family: "squat", equipment: [["leg-press"]], tags: ["machine", "legs"], singleStation: true },
  { id: "machine-hack-squat", name: "Hack Squat", category: "strength", family: "squat", equipment: [["hack-squat"]], tags: ["machine", "legs"], singleStation: true },
  { id: "smith-squat", name: "Smith Machine Squat", category: "strength", family: "squat", equipment: [["smith-machine"]], tags: ["machine", "legs"], singleStation: true },
  { id: "smith-lunge", name: "Smith Machine Lunge", category: "strength", family: "lunge", equipment: [["smith-machine"]], tags: ["machine", "unilateral"], singleStation: true },
  { id: "smith-rdl", name: "Smith Machine Romanian Deadlift", category: "strength", family: "hinge", equipment: [["smith-machine"]], tags: ["machine", "posterior-chain"], singleStation: true },
  { id: "machine-leg-extension", name: "Leg Extension", category: "strength", family: "squat", equipment: [["leg-extension"]], tags: ["machine", "quads", "accessory"], singleStation: true },
  { id: "machine-lying-leg-curl", name: "Lying Leg Curl", category: "strength", family: "hinge", equipment: [["leg-curl"]], tags: ["machine", "hamstrings", "accessory"], singleStation: true },
  { id: "machine-seated-leg-curl", name: "Seated Leg Curl", category: "strength", family: "hinge", equipment: [["leg-curl"]], tags: ["machine", "hamstrings", "accessory"], singleStation: true },
  { id: "machine-calf-raise", name: "Calf Raise Machine", category: "strength", family: "calf", equipment: [["calf-machine"]], tags: ["machine", "calves", "running-prehab"], singleStation: true },
  { id: "machine-hip-abduction", name: "Hip Abduction Machine", category: "compensation", family: "hip", equipment: [["hip-abductor-machine"]], tags: ["machine", "glutes", "prehab"], singleStation: true },
  { id: "machine-hip-adduction", name: "Hip Adduction Machine", category: "compensation", family: "hip", equipment: [["hip-adductor-machine"]], tags: ["machine", "adductors", "prehab"], singleStation: true },
  { id: "machine-hip-thrust", name: "Hip Thrust Machine", category: "strength", family: "posterior-chain", equipment: [["hip-thrust-machine"]], tags: ["machine", "glutes"], singleStation: true },
  { id: "machine-lat-pulldown-wide", name: "Wide-grip Lat Pulldown", category: "strength", family: "vertical-pull", equipment: [["lat-pulldown"]], tags: ["machine", "back"], singleStation: true },
  { id: "machine-lat-pulldown-neutral", name: "Neutral-grip Lat Pulldown", category: "strength", family: "vertical-pull", equipment: [["lat-pulldown"]], tags: ["machine", "back"], singleStation: true },
  { id: "machine-seated-row", name: "Seated Row Machine", category: "strength", family: "horizontal-pull", equipment: [["seated-row-machine"]], tags: ["machine", "back"], singleStation: true },
  { id: "machine-chest-press", name: "Chest Press Machine", category: "strength", family: "horizontal-push", equipment: [["chest-press-machine"]], tags: ["machine", "chest"], singleStation: true },
  { id: "machine-incline-chest-press", name: "Incline Chest Press Machine", category: "strength", family: "horizontal-push", equipment: [["chest-press-machine"]], tags: ["machine", "chest"], singleStation: true },
  { id: "machine-shoulder-press", name: "Shoulder Press Machine", category: "strength", family: "vertical-push", equipment: [["shoulder-press-machine"]], tags: ["machine", "shoulders"], singleStation: true },
  { id: "machine-pec-deck", name: "Pec Deck Fly", category: "strength", family: "horizontal-push", equipment: [["pec-deck"]], tags: ["machine", "chest", "accessory"], singleStation: true },
  { id: "machine-reverse-pec-deck", name: "Reverse Pec Deck", category: "compensation", family: "horizontal-pull", equipment: [["pec-deck"]], tags: ["machine", "rear-delts", "prehab"], singleStation: true },
  { id: "machine-assisted-pull-up", name: "Assisted Pull-up", category: "strength", family: "vertical-pull", equipment: [["assisted-pullup"]], tags: ["machine", "regression"], singleStation: true },
  { id: "machine-assisted-dip", name: "Assisted Dip", category: "strength", family: "horizontal-push", equipment: [["assisted-pullup"]], tags: ["machine", "regression"], singleStation: true },
  { id: "cable-row", name: "Cable Row", category: "strength", family: "horizontal-pull", equipment: [["cable-machine"]], tags: ["cable", "back"], singleStation: true },
  { id: "cable-lat-pulldown", name: "Cable Lat Pulldown", category: "strength", family: "vertical-pull", equipment: [["cable-machine"]], tags: ["cable", "back"], singleStation: true },
  { id: "face-pull", name: "Cable Face Pull", category: "compensation", family: "horizontal-pull", equipment: [["cable-machine"]], tags: ["cable", "shoulders", "prehab"], singleStation: true },
  { id: "cable-chest-fly", name: "Cable Chest Fly", category: "strength", family: "horizontal-push", equipment: [["cable-machine"]], tags: ["cable", "chest", "accessory"], singleStation: true },
  { id: "cable-reverse-fly", name: "Cable Reverse Fly", category: "compensation", family: "horizontal-pull", equipment: [["cable-machine"]], tags: ["cable", "rear-delts", "prehab"], singleStation: true },
  { id: "cable-biceps-curl", name: "Cable Biceps Curl", category: "strength", family: "arms", equipment: [["cable-machine"]], tags: ["cable", "arms", "accessory"], singleStation: true },
  { id: "cable-triceps-pushdown", name: "Cable Triceps Pushdown", category: "strength", family: "arms", equipment: [["cable-machine"]], tags: ["cable", "arms", "accessory"], singleStation: true },
  { id: "cable-overhead-triceps", name: "Cable Overhead Triceps Extension", category: "strength", family: "arms", equipment: [["cable-machine"]], tags: ["cable", "arms", "accessory"], singleStation: true },
  { id: "cable-woodchop", name: "Cable Woodchop", category: "strength", family: "core-rotation", equipment: [["cable-machine"]], tags: ["cable", "core", "finisher"], singleStation: true },
  { id: "cable-pallof-press", name: "Pallof Press", category: "compensation", family: "core-anti-rotation", equipment: [["cable-machine", "resistance-band"]], tags: ["core", "prehab"] },
  { id: "cable-glute-kickback", name: "Cable Glute Kickback", category: "strength", family: "hip", equipment: [["cable-machine"]], tags: ["cable", "glutes", "accessory"], singleStation: true },
  { id: "back-extension", name: "Back Extension", category: "strength", family: "posterior-chain", equipment: [["back-extension-bench", "ghd"]], tags: ["posterior-chain", "accessory"] },
  { id: "ghd-sit-up", name: "GHD Sit-up", category: "conditioning", family: "core-flexion", equipment: [["ghd"]], tags: ["crossfit", "core", "advanced", "finisher"], singleStation: true },

  // Cardio, functional a další conditioning
  { id: "bike-erg", name: "BikeErg", category: "conditioning", family: "cardio", equipment: [["bike-erg"]], tags: ["cardio", "engine"], singleStation: true },
  { id: "air-bike", name: "Air Bike", category: "conditioning", family: "cardio", equipment: [["air-bike"]], tags: ["cardio", "crossfit", "finisher"], singleStation: true },
  { id: "stair-climber", name: "Stair Climber", category: "conditioning", family: "cardio", equipment: [["stair-climber"]], tags: ["cardio", "legs"], singleStation: true },
  { id: "elliptical", name: "Eliptický trenažér", category: "conditioning", family: "cardio", equipment: [["elliptical"]], tags: ["cardio", "low-impact", "recovery"] },
  { id: "spin-bike", name: "Spinning Bike", category: "conditioning", family: "cardio", equipment: [["spin-bike"]], tags: ["cardio", "low-impact"] },
  { id: "jump-rope", name: "Švihadlo", category: "conditioning", family: "cardio", equipment: [["jump-rope"]], tags: ["cardio", "finisher"] },
  { id: "battle-rope-wave", name: "Battle Rope Alternating Waves", category: "conditioning", family: "conditioning", equipment: [["battle-rope"]], tags: ["functional", "upper-body", "finisher"], singleStation: true },
  { id: "battle-rope-slam", name: "Battle Rope Slam", category: "conditioning", family: "conditioning", equipment: [["battle-rope"]], tags: ["functional", "full-body", "finisher"], singleStation: true },
  { id: "medicine-ball-slam", name: "Medicine Ball Slam", category: "conditioning", family: "conditioning", equipment: [["medicine-ball"]], tags: ["functional", "full-body", "finisher"] },
  { id: "medicine-ball-clean", name: "Medicine Ball Clean", category: "conditioning", family: "olympic", equipment: [["medicine-ball"]], tags: ["crossfit", "full-body"] },
  { id: "medicine-ball-squat", name: "Medicine Ball Squat", category: "strength", family: "squat", equipment: [["medicine-ball"]], tags: ["functional"] },
  { id: "medicine-ball-thruster", name: "Medicine Ball Thruster", category: "conditioning", family: "squat", equipment: [["medicine-ball"]], tags: ["functional", "wall-ball-alternative", "finisher"] },
  { id: "sandbag-carry", name: "Sandbag Carry", category: "conditioning", family: "carry", equipment: [["sandbag"]], tags: ["functional", "grip"] },
  { id: "sandbag-shoulder", name: "Sandbag to Shoulder", category: "conditioning", family: "conditioning", equipment: [["sandbag"]], tags: ["functional", "full-body", "finisher"] },
  { id: "sandbag-squat", name: "Sandbag Squat", category: "strength", family: "squat", equipment: [["sandbag"]], tags: ["functional", "legs"] },

  // Mobilita, kompenzace, prehab a cooldown
  { id: "cat-cow", name: "Cat-Cow", category: "mobility", family: "mobility", tags: ["spine", "warmup"] },
  { id: "childs-pose", name: "Child's Pose", category: "recovery", family: "mobility", tags: ["spine", "cooldown"] },
  { id: "couch-stretch", name: "Couch Stretch", category: "mobility", family: "mobility", tags: ["hips", "quads", "cooldown"] },
  { id: "calf-stretch", name: "Calf Stretch", category: "mobility", family: "mobility", tags: ["calves", "running-prehab", "cooldown"] },
  { id: "hamstring-stretch", name: "Hamstring Stretch", category: "mobility", family: "mobility", tags: ["hamstrings", "cooldown"] },
  { id: "adductor-rockback", name: "Adductor Rockback", category: "mobility", family: "mobility", tags: ["hips", "adductors", "prehab"] },
  { id: "hip-90-90", name: "90/90 Hip Switch", category: "mobility", family: "mobility", tags: ["hips", "rotation"] },
  { id: "pigeon-stretch", name: "Pigeon Stretch", category: "mobility", family: "mobility", tags: ["hips", "glutes", "cooldown"] },
  { id: "figure-four-stretch", name: "Figure Four Stretch", category: "mobility", family: "mobility", tags: ["hips", "glutes", "cooldown"] },
  { id: "deep-squat-hold", name: "Deep Squat Hold", category: "mobility", family: "squat", tags: ["hips", "ankles", "warmup"] },
  { id: "worlds-greatest-stretch", name: "World's Greatest Stretch", category: "warmup", family: "mobility", tags: ["full-body", "hips", "t-spine"] },
  { id: "cossack-squat", name: "Cossack Squat", category: "mobility", family: "lunge", tags: ["hips", "adductors", "strength-mobility"] },
  { id: "open-book", name: "Open Book Rotation", category: "mobility", family: "mobility", tags: ["t-spine", "shoulders"] },
  { id: "thread-the-needle", name: "Thread the Needle", category: "mobility", family: "mobility", tags: ["t-spine", "shoulders"] },
  { id: "wall-slide", name: "Wall Slide", category: "compensation", family: "shoulder", tags: ["shoulders", "scapula", "prehab"] },
  { id: "scapular-push-up", name: "Scapular Push-up", category: "compensation", family: "shoulder", tags: ["shoulders", "scapula", "prehab"] },
  { id: "band-face-pull", name: "Band Face Pull", category: "compensation", family: "horizontal-pull", equipment: [["resistance-band"]], tags: ["shoulders", "prehab"] },
  { id: "band-external-rotation", name: "Band External Rotation", category: "compensation", family: "shoulder", equipment: [["resistance-band"]], tags: ["rotator-cuff", "prehab"] },
  { id: "band-internal-rotation", name: "Band Internal Rotation", category: "compensation", family: "shoulder", equipment: [["resistance-band"]], tags: ["rotator-cuff", "prehab"] },
  { id: "band-row", name: "Band Row", category: "compensation", family: "horizontal-pull", equipment: [["resistance-band"]], tags: ["back", "prehab"] },
  { id: "band-lateral-walk", name: "Band Lateral Walk", category: "compensation", family: "hip", equipment: [["resistance-band"]], tags: ["glutes", "running-prehab"] },
  { id: "monster-walk", name: "Monster Walk", category: "compensation", family: "hip", equipment: [["resistance-band"]], tags: ["glutes", "running-prehab"] },
  { id: "clamshell", name: "Clamshell", category: "compensation", family: "hip", equipment: [["resistance-band", "none"]], tags: ["glutes", "prehab"] },
  { id: "side-lying-leg-raise", name: "Side-lying Leg Raise", category: "compensation", family: "hip", tags: ["glutes", "prehab"] },
  { id: "heel-tap", name: "Dead Bug Heel Tap", category: "compensation", family: "core", tags: ["core", "prehab"] },
  { id: "pelvic-tilt", name: "Pelvic Tilt", category: "compensation", family: "core", tags: ["core", "low-back", "recovery"] },
  { id: "mcgill-curl-up", name: "McGill Curl-up", category: "compensation", family: "core", tags: ["core", "low-back", "prehab"] },
  { id: "side-plank-knee", name: "Side Plank from Knees", category: "compensation", family: "core", tags: ["core", "regression", "prehab"] },
  { id: "breathing-90-90", name: "90/90 Breathing", category: "recovery", family: "mobility", tags: ["breathing", "recovery", "core"] },
  { id: "diaphragmatic-breathing", name: "Diaphragmatic Breathing", category: "recovery", family: "mobility", tags: ["breathing", "recovery", "cooldown"] },
  { id: "standing-quad-stretch", name: "Standing Quad Stretch", category: "mobility", family: "mobility", tags: ["quads", "cooldown"] },
  { id: "triceps-stretch", name: "Triceps Stretch", category: "mobility", family: "mobility", tags: ["arms", "shoulders", "cooldown"] },
  { id: "lat-stretch", name: "Lat Stretch", category: "mobility", family: "mobility", tags: ["back", "shoulders", "cooldown"] },
  { id: "wrist-mobility", name: "Wrist Mobility", category: "mobility", family: "mobility", tags: ["wrists", "crossfit", "warmup"] },
  { id: "ankle-calf-pulse", name: "Ankle Calf Pulse", category: "warmup", family: "calf", tags: ["ankles", "calves", "running-prehab"] },
];

export const EXTENDED_EXERCISE_LIBRARY: ExerciseDefinition[] = SEEDS.map(build);
