import type { ExerciseDefinition } from "./exercise-library";

const solo = { modes: ["solo", "simultaneous"] as const, supportsIndependentTracking: true };

export const RECOVERY_EXERCISE_LIBRARY: ExerciseDefinition[] = [
  {
    id: "recovery-worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    aliases: ["worlds greatest stretch", "greatest stretch"],
    category: "mobility",
    movementFamily: "full-body-mobility",
    equipment: [],
    primaryMuscles: ["kyčle", "hamstringy", "hrudní páteř"],
    purposes: ["dynamické rozcvičení", "mobilita kyčlí", "rotace hrudní páteře"],
    instructions: ["Přejdi do dlouhého výpadu a opři dlaň o zem.", "Rotuj hrudník směrem k přední noze a vrať se kontrolovaně zpět."],
    cues: ["Dlouhá páteř", "Přední chodidlo celé na zemi", "Rotace z hrudníku"],
    commonMistakes: ["Koleno padá dovnitř", "Rotace pouze z bederní páteře"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-90-90-hip-switch"],
    tags: ["warmup", "mobility", "full-body", "hips", "thoracic", "prehab"],
    team: solo,
  },
  {
    id: "recovery-90-90-hip-switch",
    name: "90/90 Hip Switch",
    aliases: ["90 90 hip switch", "hip switch"],
    category: "mobility",
    movementFamily: "hip-rotation",
    equipment: [{ anyOf: ["none", "mat"] }],
    primaryMuscles: ["kyčle", "hýždě"],
    purposes: ["rotace kyčlí", "mobilita", "příprava na dřepy a výpady"],
    instructions: ["Sedni si do pozice 90/90 a překlápěj obě kolena ze strany na stranu.", "Rozsah drž jen tak velký, aby pohyb zůstal plynulý."],
    cues: ["Hrudník vysoko", "Pomalý přechod", "Bez násilí do rozsahu"],
    commonMistakes: ["Švih koleny", "Bolestivý tlak do kyčle"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-adductor-rockback"],
    tags: ["mobility", "hips", "warmup", "recovery", "prehab"],
    team: solo,
  },
  {
    id: "recovery-adductor-rockback",
    name: "Adductor Rockback",
    aliases: ["adductor rockback", "adductor rock back"],
    category: "mobility",
    movementFamily: "hip-adduction-mobility",
    equipment: [{ anyOf: ["none", "mat"] }],
    primaryMuscles: ["adduktory", "kyčle"],
    purposes: ["mobilita adduktorů", "dřep", "výpady"],
    instructions: ["Z kleku natáhni jednu nohu do strany a posouvej pánev dozadu.", "Vrať se dopředu bez rotace pánve."],
    cues: ["Chodidlo na zemi", "Pánev rovně", "Plynulý dech"],
    commonMistakes: ["Rotace pánve", "Příliš agresivní rozsah"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-90-90-hip-switch"],
    tags: ["mobility", "hips", "adductors", "warmup", "prehab"],
    team: solo,
  },
  {
    id: "recovery-couch-stretch",
    name: "Couch Stretch",
    aliases: ["couch stretch", "hip flexor couch stretch"],
    category: "mobility",
    movementFamily: "hip-extension-mobility",
    equipment: [{ anyOf: ["none", "bench", "box", "mat"] }],
    primaryMuscles: ["flexory kyčle", "kvadricepsy"],
    purposes: ["mobilita přední strany kyčle", "cool-down", "kompenzace po běhu a výpadech"],
    instructions: ["Opři zadní koleno o měkký podklad a nárt o stěnu nebo lavici.", "Podsazením pánve najdi tah v přední straně stehna a kyčle."],
    cues: ["Žebra nad pánví", "Hýždě lehce aktivní", "Bez prohnutí beder"],
    commonMistakes: ["Velký záklon", "Tlak přes bolest kolene"],
    regressions: [],
    progressions: [],
    alternatives: ["hip-flexor-stretch"],
    tags: ["mobility", "hips", "quads", "cooldown", "recovery"],
    team: solo,
  },
  {
    id: "recovery-knee-to-wall",
    name: "Knee-to-Wall Ankle Rock",
    aliases: ["knee to wall", "ankle rock", "ankle dorsiflexion"],
    category: "mobility",
    movementFamily: "ankle-mobility",
    equipment: [],
    primaryMuscles: ["kotník", "lýtka"],
    purposes: ["dorzální flexe kotníku", "příprava na běh", "příprava na dřep"],
    instructions: ["Postav chodidlo několik centimetrů od stěny a posouvej koleno vpřed nad špičku.", "Patu drž po celou dobu na zemi."],
    cues: ["Pata dole", "Koleno sleduje směr prstů", "Pomalý návrat"],
    commonMistakes: ["Zvedání paty", "Koleno padá dovnitř"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-soleus-stretch"],
    tags: ["mobility", "ankles", "calves", "running", "warmup", "prehab"],
    team: solo,
  },
  {
    id: "recovery-soleus-stretch",
    name: "Soleus Stretch",
    aliases: ["soleus stretch", "bent knee calf stretch"],
    category: "mobility",
    movementFamily: "calf-mobility",
    equipment: [],
    primaryMuscles: ["lýtka", "kotník"],
    purposes: ["mobilita lýtka", "recovery po běhu", "kotník"],
    instructions: ["Při patě na zemi lehce pokrč koleno a posuň ho vpřed.", "Drž tah v dolní části lýtka bez odlepování paty."],
    cues: ["Pata dole", "Malý kontrolovaný rozsah", "Klidný dech"],
    commonMistakes: ["Odlepení paty", "Příliš hluboký tlak"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-knee-to-wall"],
    tags: ["mobility", "ankles", "calves", "cooldown", "running", "recovery"],
    team: solo,
  },
  {
    id: "recovery-glute-bridge",
    name: "Glute Bridge Activation",
    aliases: ["glute bridge activation", "glute bridge"],
    category: "warmup",
    movementFamily: "hip-extension",
    equipment: [{ anyOf: ["none", "mat"] }],
    primaryMuscles: ["hýždě", "hamstringy", "core"],
    purposes: ["aktivace hýždí", "příprava na běh", "příprava na hip hinge"],
    instructions: ["Lehni si na záda, chodidla dej pod kolena a zvedni pánev.", "Nahoře krátce zatni hýždě bez prohnutí beder."],
    cues: ["Žebra dolů", "Tlak přes celé chodidlo", "Hýždě dokončí pohyb"],
    commonMistakes: ["Propínání přes bedra", "Tlak jen přes špičky"],
    regressions: [],
    progressions: ["single-leg-glute-bridge"],
    alternatives: ["recovery-band-lateral-walk"],
    tags: ["warmup", "activation", "hips", "glutes", "posterior-chain", "prehab"],
    team: solo,
  },
  {
    id: "recovery-band-lateral-walk",
    name: "Band Lateral Walk",
    aliases: ["band lateral walk", "monster walk"],
    category: "warmup",
    movementFamily: "hip-abduction",
    equipment: [{ anyOf: ["resistance-band"] }],
    primaryMuscles: ["hýždě", "abduktory kyčle"],
    purposes: ["aktivace hýždí", "stabilita kolene", "příprava na dřepy a běh"],
    instructions: ["Drž lehký podřep a dělej krátké kroky do strany proti odporu gumy.", "Kolena drž v ose chodidel."],
    cues: ["Pánev stabilní", "Krátké kroky", "Kolena ven"],
    commonMistakes: ["Spojování chodidel", "Houpání trupu"],
    regressions: ["recovery-glute-bridge"],
    progressions: [],
    alternatives: ["recovery-glute-bridge"],
    tags: ["warmup", "activation", "hips", "glutes", "knees", "prehab"],
    team: solo,
  },
  {
    id: "recovery-band-external-rotation",
    name: "Band External Rotation",
    aliases: ["band external rotation", "shoulder external rotation"],
    category: "compensation",
    movementFamily: "shoulder-external-rotation",
    equipment: [{ anyOf: ["resistance-band"] }],
    primaryMuscles: ["rotátorová manžeta", "ramena"],
    purposes: ["aktivace ramene", "prehab", "příprava na tlakové a tahové cviky"],
    instructions: ["Loket drž u těla a předloktí rotuj ven proti lehkému odporu gumy.", "Pohyb veď z ramene bez rotace trupu."],
    cues: ["Loket u žeber", "Lehký odpor", "Lopatka stabilní"],
    commonMistakes: ["Rotace celého trupu", "Příliš silná guma"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-wall-slide"],
    tags: ["prehab", "shoulders", "warmup", "activation", "upper-body"],
    team: solo,
  },
  {
    id: "recovery-wall-slide",
    name: "Wall Slide",
    aliases: ["wall slide", "shoulder wall slide"],
    category: "compensation",
    movementFamily: "scapular-control",
    equipment: [],
    primaryMuscles: ["lopatky", "ramena", "hrudní páteř"],
    purposes: ["kontrola lopatek", "mobilita ramen", "příprava nad hlavu"],
    instructions: ["Opři záda a předloktí o stěnu a pomalu posouvej paže vzhůru.", "Rozsah ukonči před ztrátou kontaktu žeber a zad se stěnou."],
    cues: ["Žebra dolů", "Ramena od uší", "Pomalý pohyb"],
    commonMistakes: ["Prohnutí beder", "Krčení ramen"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-band-external-rotation"],
    tags: ["prehab", "shoulders", "thoracic", "warmup", "mobility"],
    team: solo,
  },
  {
    id: "recovery-band-face-pull",
    name: "Band Face Pull",
    aliases: ["band face pull", "face pull"],
    category: "compensation",
    movementFamily: "horizontal-pull",
    equipment: [{ anyOf: ["resistance-band", "cable-machine"] }],
    primaryMuscles: ["zadní ramena", "lopatky", "horní záda"],
    purposes: ["kompenzace tlaků", "lopatková stabilita", "prehab ramene"],
    instructions: ["Táhni gumu nebo lano směrem k obličeji a lokty veď do stran.", "V konci pohybu stáhni lopatky bez záklonu."],
    cues: ["Hrudník klidný", "Lokty vysoko", "Lopatky dozadu"],
    commonMistakes: ["Záklon trupu", "Tah pouze bicepsem"],
    regressions: ["band-pull-apart"],
    progressions: [],
    alternatives: ["recovery-wall-slide"],
    tags: ["prehab", "shoulders", "upper-back", "upper-body", "compensation"],
    team: solo,
  },
  {
    id: "recovery-doorway-pec-stretch",
    name: "Doorway Pec Stretch",
    aliases: ["doorway pec stretch", "pec stretch"],
    category: "mobility",
    movementFamily: "shoulder-extension-mobility",
    equipment: [],
    primaryMuscles: ["prsní svaly", "ramena"],
    purposes: ["cool-down po tlacích", "mobilita hrudníku", "kompenzace přední strany ramen"],
    instructions: ["Opři předloktí o rám nebo pevnou hranu a lehce otoč trup od paže.", "Tah drž v prsním svalu, ne v přední části ramene."],
    cues: ["Rameno od ucha", "Lehký tah", "Bez bolesti"],
    commonMistakes: ["Tlak do přední části ramene", "Příliš agresivní rotace"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-wall-slide"],
    tags: ["mobility", "shoulders", "chest", "cooldown", "recovery"],
    team: solo,
  },
  {
    id: "recovery-thread-the-needle",
    name: "Thread the Needle",
    aliases: ["thread the needle", "thoracic rotation"],
    category: "mobility",
    movementFamily: "thoracic-rotation",
    equipment: [{ anyOf: ["none", "mat"] }],
    primaryMuscles: ["hrudní páteř", "horní záda", "ramena"],
    purposes: ["rotace hrudní páteře", "mobilita zad", "cool-down"],
    instructions: ["Z pozice na čtyřech protáhni jednu paži pod tělem a rotuj hrudník.", "Vrať se a otevři paži vzhůru jen v pohodlném rozsahu."],
    cues: ["Pánev klidná", "Rotace z hrudníku", "Pomalý dech"],
    commonMistakes: ["Rotace pánve", "Švih paží"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-cat-cow"],
    tags: ["mobility", "thoracic", "upper-back", "recovery", "cooldown"],
    team: solo,
  },
  {
    id: "recovery-cat-cow",
    name: "Cat-Cow",
    aliases: ["cat cow", "cat-cow"],
    category: "mobility",
    movementFamily: "spine-mobility",
    equipment: [{ anyOf: ["none", "mat"] }],
    primaryMuscles: ["páteř", "core", "záda"],
    purposes: ["mobilita páteře", "zklidnění", "dech"],
    instructions: ["Na čtyřech střídej pomalé vyhrbení a prohnutí páteře.", "Spoj pohyb s klidným nádechem a výdechem."],
    cues: ["Pomalý pohyb", "Bez krajních poloh", "Dech vede pohyb"],
    commonMistakes: ["Rychlé švihání", "Tlačení do nepříjemného rozsahu"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-thread-the-needle"],
    tags: ["mobility", "spine", "back", "recovery", "cooldown"],
    team: solo,
  },
  {
    id: "recovery-bench-thoracic-extension",
    name: "Bench Thoracic Extension",
    aliases: ["thoracic extension on bench", "bench thoracic extension"],
    category: "mobility",
    movementFamily: "thoracic-extension",
    equipment: [{ anyOf: ["bench", "box"] }],
    primaryMuscles: ["hrudní páteř", "latissimy", "ramena"],
    purposes: ["mobilita hrudní páteře", "příprava nad hlavu", "kompenzace po SkiErgu a tlacích"],
    instructions: ["Klekni si před lavici, lokty polož na hranu a spusť hrudník mezi paže.", "Bedra drž neutrálně a rozsah hledej v hrudní páteři."],
    cues: ["Žebra dolů", "Hrudník mezi paže", "Klidný dech"],
    commonMistakes: ["Prohnutí beder", "Tlak ramen přes bolest"],
    regressions: ["recovery-wall-slide"],
    progressions: [],
    alternatives: ["recovery-thread-the-needle"],
    tags: ["mobility", "thoracic", "shoulders", "lats", "warmup", "cooldown"],
    team: solo,
  },
  {
    id: "recovery-hamstring-floss",
    name: "Hamstring Floss",
    aliases: ["hamstring floss", "hamstring mobilization"],
    category: "mobility",
    movementFamily: "posterior-chain-mobility",
    equipment: [],
    primaryMuscles: ["hamstringy", "lýtka"],
    purposes: ["dynamická mobilita zadní strany", "příprava na běh", "cool-down"],
    instructions: ["Střídej lehké pokrčení a propnutí kolene s neutrální páteří.", "Nevydržuj dlouho v krajní pozici."],
    cues: ["Plynulý pohyb", "Rovná záda", "Bez tahání přes bolest"],
    commonMistakes: ["Agresivní statický tah", "Kulatá bedra"],
    regressions: [],
    progressions: [],
    alternatives: ["recovery-soleus-stretch"],
    tags: ["mobility", "hamstrings", "posterior-chain", "running", "warmup", "cooldown"],
    team: solo,
  },
  {
    id: "recovery-breathing-reset",
    name: "Breathing Reset",
    aliases: ["breathing reset", "recovery breathing"],
    category: "recovery",
    movementFamily: "breathing",
    equipment: [{ anyOf: ["none", "mat"] }],
    primaryMuscles: ["bránice", "core"],
    purposes: ["zklidnění po tréninku", "recovery", "kontrola dechu"],
    instructions: ["Lehni si nebo sedni pohodlně a prodluž výdech oproti nádechu.", "Drž dech klidný a bez nucení do maximálních nádechů."],
    cues: ["Dlouhý výdech", "Uvolněná ramena", "Pomalé tempo"],
    commonMistakes: ["Příliš hluboké nucené nádechy", "Zadržování dechu"],
    regressions: [],
    progressions: [],
    alternatives: ["breathing-90-90"],
    tags: ["recovery", "cooldown", "breathing", "full-body"],
    team: solo,
  },
  {
    id: "recovery-wrist-rock",
    name: "Wrist Rock",
    aliases: ["wrist rock", "wrist mobility"],
    category: "mobility",
    movementFamily: "wrist-mobility",
    equipment: [{ anyOf: ["none", "mat"] }],
    primaryMuscles: ["zápěstí", "předloktí"],
    purposes: ["příprava zápěstí", "gymnastika", "front rack a vzpírání"],
    instructions: ["Na čtyřech polož dlaně na zem a pomalu přenášej váhu vpřed a zpět.", "Rozsah drž pohodlný a lokty měkké."],
    cues: ["Celá dlaň na zemi", "Pomalý přenos váhy", "Bez ostré bolesti"],
    commonMistakes: ["Rychlé pružení", "Tlak do nepříjemné krajní polohy"],
    regressions: [],
    progressions: [],
    alternatives: [],
    tags: ["mobility", "wrists", "warmup", "crossfit", "gymnastics", "prehab"],
    team: solo,
  },
];
